apiVersion: v1
kind: PersistentVolumeClaim
namespace: nextcloud
metadata:
  name: nextcloud-pvc
  labels:
    app: nextcloud
spec:
  resources:
    requests:
      storage: 256Mi
#  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
