apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  labels:
    app: nextcloud
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"